### ISSUE TITLE
`isFalsyExtended` not working properly

### ISSUE THREAD

**Issue by m10rten** [m10rten/validatees#97]
When passing an object with values that are undefined or null, it should not return false because thats not how this function should work.

In that way an option parameter can be passed to tell the function to either do or do not behave a certain way.

**Comment by anoop-dev0** [comment]
Hey @m10rten ,
I think this can be done only by removing these lines from isFalsyExtended.ts

```
true === Object.keys(value).some((key) => true === isFalsy(value[key])) ||
      true === Object.values(value).some((val: any) => true === isFalsy(val))
```

**Comment by m10rten** [comment]
> Hey @m10rten ,
> I think this can be done only by removing these lines from isFalsyExtended.ts
> 
> ```
> true === Object.keys(value).some((key) => true === isFalsy(value[key])) ||
>       true === Object.values(value).some((val: any) => true === isFalsy(val))
> ```
> 
> 
> 
> 
> 
> 

Thank you for commenting on this!
Yes, that is very much the way to go.
But Ive thought of having an options param for deepsearch falsy checks.

**Comment by anoop-dev0** [comment]
Sure.
I just want to understand the use case of sending a flag for deepsearch.

**Comment by m10rten** [comment]
> Sure. I just want to understand the use case of sending a flag for deepsearch.

Usecase to use its falsy "power" as to call it,, within an object deep search.
Lets say you have 3 layers down: 
Array > object: arr > Array
And you want to make sure every item in the last array is not falsy or truthy.

You can put Array[0].arr in the function, but what if you wanted to check all arrays of Array at once: just put the array in, let the function handle the rest

**Comment by anoop-dev0** [comment]
@m10rten Right, I will try to come up with a solution asap.

**Comment by m10rten** [comment]
great @anoop-dev0 , I've pushed some deps updates to dev, might want to pull those in.
